name: Book Tee Time

on:
  schedule:
    # This cron schedule triggers the workflow at a specific date and time.
    # To book for a new date, calculate the date 7 days before your desired booking date
    # and update the cron expression below. Example: To book for 2025-05-27,
    # calculate 7 days before (2025-05-20) and set cron to '0 5 20 5 *'.
    - cron: '0 5 * * *' # Current cron: Runs daily at 5:00 AM UTC
  workflow_dispatch:
    inputs:
      email:
        description: 'PBC login email'
        required: true
        type: string
      password:
        description: 'PBC login password'
        required: true
        type: string
      date:
        description: 'Date to book (YYYY-MM-DD)'
        required: true
        type: string
      time_range_start:
        description: 'Start time of range (HH:MM)'
        required: true
        type: string
      time_range_end:
        description: 'End time of range (HH:MM)'
        required: true
        type: string
      players:
        description: 'Number of players (1-4)'
        required: true
        type: number

jobs:
  book-tee-time:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright
      run: |
        playwright install
        playwright install-deps
        
    - name: Run booking script
      env:
        EMAIL: ${{ github.event.inputs.email }}
        PASSWORD: ${{ github.event.inputs.password }}
        DATE: ${{ github.event.inputs.date }}
        TIME_RANGE_START: ${{ github.event.inputs.time_range_start }}
        TIME_RANGE_END: ${{ github.event.inputs.time_range_end }}
        PLAYERS: ${{ github.event.inputs.players }}
      run: python book_tee_time.py 