name: Tee Time Booking

on:
  schedule:
    # Run every Saturday and Sunday at 5:00 AM and 6:00 AM EST (10:00 AM and 11:00 AM UTC)
    - cron: '0 10,11 * * 6,0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  book-tee-time:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Playwright
      run: |
        pip install playwright==1.42.0 python-dotenv==1.0.0
        playwright install chromium
        
    - name: Create .env file
      run: |
        cat << EOF > .env
        TIME_RANGE_START=${{ secrets.TIME_RANGE_START }}
        TIME_RANGE_END=${{ secrets.TIME_RANGE_END }}
        PLAYERS=${{ secrets.PLAYERS }}
        EMAIL=${{ secrets.EMAIL }}
        PASSWORD=${{ secrets.PASSWORD }}
        OSPREY_ONLY=${{ secrets.OSPREY_ONLY }}
        EOF
        
    - name: Run booking script
      run: python book_tee_time.py
      
    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: booking-screenshots
        path: |
          *.png
          cron_script_run.log 