name: Tee Time Booking

on:
  schedule:
    # Run every Saturday and Sunday at 4:45 AM EST (9:45 AM UTC) - 15 min before target time
    - cron: '55 9,10 * * 6,0'

  workflow_dispatch:  # Allow manual triggering

jobs:
  book-tee-time:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Playwright
      run: |
        pip install playwright==1.42.0 python-dotenv==1.0.0
        playwright install chromium
        
    - name: Create .env file
      run: |
        cat << EOF > .env
        TIME_RANGE_START=${{ secrets.TIME_RANGE_START || '07:00' }}
        TIME_RANGE_END=${{ secrets.TIME_RANGE_END || '12:00' }}
        PLAYERS=${{ secrets.PLAYERS || '4' }}
        EMAIL=${{ secrets.EMAIL }}
        PASSWORD=${{ secrets.PASSWORD }}
        OSPREY_ONLY=${{ secrets.OSPREY_ONLY || 'true' }}
        EOF
        
    - name: Run booking script
      run: python book_tee_time.py
      
    - name: Upload screenshots as artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: booking-screenshots
        path: |
          *.png
          cron_script_run.log 